set nu
filetype on
set history=1000
set background=dark
syntax on
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set showmatch
set nohls
set ruler
colorscheme evening
set guifont=courier_new:h15
set backspace=indent,eol,start